=== Infineon/edgeprotecttools/src/targets/common/mxs22/debug_token/schemas/debug_token_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "device_id": {
      "type": "object",
      "properties": {
        "family_id": {
          "type": "string"
        },
        "si_revision_id": {
          "type": "string"
        }
      },
      "required": [
        "family_id",
        "si_revision_id"
      ]
    },
    "silicon_id": {
      "type": "string"
    },
    "control_word": {
      "type": "object",
      "properties": {
        "system": {
          "type": "object",
          "properties": {
            "ap": {
              "type": "string",
              "enum": [
                "Enabled",
                "Disabled"
              ]
            }
          },
          "required": [
            "ap"
          ]
        },
        "cm33_0": {
          "type": "object",
          "properties": {
            "ap": {
              "type": "string",
              "enum": [
                "Enabled",
                "Disabled"
              ]
            },
            "dbgen": {
              "type": "boolean"
            },
            "niden": {
              "type": "boolean"
            },
            "spiden": {
              "type": "boolean"
            },
            "spniden": {
              "type": "boolean"
            },
            "secure": {
              "type": "boolean"
            }
          },
          "required": [
            "ap",
            "dbgen",
            "niden",
            "spiden",
            "spniden",
            "secure"
          ]
        }
      },
      "required": [
        "system",
        "cm33_0"
      ]
    },
    "die_id": {
      "type": "object",
      "properties": {
        "max": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "day",
            "month",
            "year"
          ]
        },
        "min": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "day",
            "month",
            "year"
          ]
        }
      },
      "required": [
        "max",
        "min"
      ]
    }
  },
  "required": [
    "version",
    "device_id",
    "silicon_id",
    "control_word",
    "die_id"
  ]
}

=== Infineon/edgeprotecttools/src/targets/pse8xs2_b1/packets/debug_token.json
{
  "version": "1.0.0.0",
  "device_id": {
    "family_id": "0x0115",
    "si_revision_id": "0x22"
  },
  "silicon_id": "0xF181",
  "control_word": {
    "system": {
      "ap": "Enabled"
    },
    "cm33_0": {
      "ap": "Enabled",
      "dbgen": true,
      "niden": true,
      "spiden": true,
      "spniden": true,
      "secure": true
    }
  },
  "die_id": {
    "min": {
      "lot": 0,
      "wafer": 0,
      "xpos": 0,
      "ypos": 0,
      "sort": 0,
      "day": 0,
      "month": 0,
      "year": 0
    },
    "max": {
      "lot": 16777215,
      "wafer": 255,
      "xpos": 255,
      "ypos": 255,
      "sort": 255,
      "day": 255,
      "month": 255,
      "year": 255
    }
  }
}
