=== Infineon/edgeprotecttools/src/targets/common/mxs22/debug_token/schemas/rma_token_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "device_id": {
      "type": "object",
      "properties": {
        "family_id": {
          "type": "string"
        },
        "si_revision_id": {
          "type": "string"
        }
      },
      "required": [
        "family_id",
        "si_revision_id"
      ]
    },
    "silicon_id": {
      "type": "string"
    },
    "die_id": {
      "type": "object",
      "properties": {
        "max": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "day",
            "month",
            "year"
          ]
        },
        "min": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "day",
            "month",
            "year"
          ]
        }
      },
      "required": [
        "max",
        "min"
      ]
    },
    "rram_sections": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
            "address": {
              "type": "string"
            },
            "size": {
              "type": "string"
            }
        },
        "required": [
          "address",
          "size"
        ]
      }
    }
  },
  "required": [
    "version",
    "device_id",
    "silicon_id",
    "die_id",
    "rram_sections"
  ]
}

=== Infineon/edgeprotecttools/src/targets/pse8xs4_b1/packets/rma_token.json
{
  "version": "1.0.0.0",
  "device_id": {
    "family_id": "0x0115",
    "si_revision_id": "0x22"
  },
  "silicon_id": "0xF180",
  "die_id": {
    "min": {
      "lot": 0,
      "wafer": 0,
      "xpos": 0,
      "ypos": 0,
      "sort": 0,
      "day": 0,
      "month": 0,
      "year": 0
    },
    "max": {
      "lot": 16777215,
      "wafer": 255,
      "xpos": 255,
      "ypos": 255,
      "sort": 255,
      "day": 255,
      "month": 255,
      "year": 255
    }
  },
  "rram_sections": []
}
