=== Infineon/edgeprotecttools/src/targets/psoc_c3/schemas/prot_fw_enc_key_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Protected FW Encrypted Key Policy Schema",
    "type": "object",
    "required": [
        "policy",
        "mode",
        "public_key",
        "ciphertext"
    ],
    "properties": {
        "policy": {
            "type": "object",
            "required": [
                "platform",
                "version",
                "type"
            ],
            "properties": {
                "platform": {
                    "type": "string"
                },
                "version": {
                    "type": "number",
                    "minimum": 1.0,
                    "maximum": 99.99
                },
                "type": {
                    "type": "string",
                    "const": "prot_fw_enc_key"
                }
            }
        },
        "mode": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string",
                    "enum": [
                        "KEY_GEN",
                        "KEY_INSTALL"
                    ]
                }
            }
        },
        "public_key": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "ciphertext": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        }
    }
}

=== Infineon/edgeprotecttools/src/targets/psoc_c3/policy/policy_prot_fw_enc_key.json
{
  "policy": {
    "platform": "psoc_c3",
    "version": 1.0,
    "type": "prot_fw_enc_key"
  },
  "mode": {
    "description": "Indicates which mode to use",
    "applicable_conf": "KEY_GEN, KEY_INSTALL",
    "value": "KEY_GEN"
  },
  "public_key": {
    "description": "Path to the public key used for ECIES for KEY_INSTALL mode",
    "value": ""
  },
  "ciphertext":{
    "description": "Encrypted PROT_FW_KEY used for KEY_INSTALL mode",
    "value": ""
  }
}
